-- Update Team

-- !Ups
ALTER TABLE Secret ALTER a VARCHAR(2000) NOT NULL;
ALTER TABLE Secret ALTER r VARCHAR(2000) NOT NULL;

-- !Downs
ALTER TABLE Secret ALTER a VARCHAR(1000) NOT NULL;
ALTER TABLE Secret ALTER r VARCHAR(1000) NOT NULL;
